//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DouBanFMBase.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DouBanFMBase.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于此应用 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掌三豆瓣FM是一款第三方的豆瓣FM应用，应用版权归开发者所有 的本地化字符串。
        /// </summary>
        public static string AboutAppTip {
            get {
                return ResourceManager.GetString("AboutAppTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        public static string AccountEmpty {
            get {
                return ResourceManager.GetString("AccountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入你要登录的账号 的本地化字符串。
        /// </summary>
        public static string AccountTip {
            get {
                return ResourceManager.GetString("AccountTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先登录，才能添加红心歌曲 的本地化字符串。
        /// </summary>
        public static string AddLoveSongTip {
            get {
                return ResourceManager.GetString("AddLoveSongTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已阅读并同意 的本地化字符串。
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;账号协议和隐私条款&gt; 的本地化字符串。
        /// </summary>
        public static string AgreementInfo {
            get {
                return ResourceManager.GetString("AgreementInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选用户协议后，才可进行注册 的本地化字符串。
        /// </summary>
        public static string AgreementTip {
            get {
                return ResourceManager.GetString("AgreementTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部兆赫 的本地化字符串。
        /// </summary>
        public static string AllHz {
            get {
                return ResourceManager.GetString("AllHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单项 的本地化字符串。
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的应用程序 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用设置 的本地化字符串。
        /// </summary>
        public static string AppSetting {
            get {
                return ResourceManager.GetString("AppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wifi网络下自动下载当前添加的红心歌曲 的本地化字符串。
        /// </summary>
        public static string AutoDownSongInWifi {
            get {
                return ResourceManager.GetString("AutoDownSongInWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换账号 的本地化字符串。
        /// </summary>
        public static string ChangeAccount {
            get {
                return ResourceManager.GetString("ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏兆赫 的本地化字符串。
        /// </summary>
        public static string CollectHz {
            get {
                return ResourceManager.GetString("CollectHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要退出应用 的本地化字符串。
        /// </summary>
        public static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在使用手机移动网络，将产生手机流量消耗 的本地化字符串。
        /// </summary>
        public static string CostTip {
            get {
                return ResourceManager.GetString("CostTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义主题 的本地化字符串。
        /// </summary>
        public static string CustomTheme {
            get {
                return ResourceManager.GetString("CustomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 豆瓣FM登录 的本地化字符串。
        /// </summary>
        public static string DbLoginTitle {
            get {
                return ResourceManager.GetString("DbLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除选定歌曲 的本地化字符串。
        /// </summary>
        public static string DeleteSongsTip {
            get {
                return ResourceManager.GetString("DeleteSongsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 猜你喜欢 的本地化字符串。
        /// </summary>
        public static string DoyouLike {
            get {
                return ResourceManager.GetString("DoyouLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        public static string EnLang {
            get {
                return ResourceManager.GetString("EnLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出时停止播放音乐 的本地化字符串。
        /// </summary>
        public static string ExitStopMusicTip {
            get {
                return ResourceManager.GetString("ExitStopMusicTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意见反馈 的本地化字符串。
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为我打分 的本地化字符串。
        /// </summary>
        public static string GradeForMe {
            get {
                return ResourceManager.GetString("GradeForMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有账号,登录 的本地化字符串。
        /// </summary>
        public static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置 的本地化字符串。
        /// </summary>
        public static string LangSetting {
            get {
                return ResourceManager.GetString("LangSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先登录，才能收听红心HZ 的本地化字符串。
        /// </summary>
        public static string ListenLoveRadioTip {
            get {
                return ResourceManager.GetString("ListenLoveRadioTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击加载频道列表 的本地化字符串。
        /// </summary>
        public static string LoadChannelTip {
            get {
                return ResourceManager.GetString("LoadChannelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先从本地图库添加主题图片 的本地化字符串。
        /// </summary>
        public static string LoadThemeFirst {
            get {
                return ResourceManager.GetString("LoadThemeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先登录 的本地化字符串。
        /// </summary>
        public static string LoginFirst {
            get {
                return ResourceManager.GetString("LoginFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人中心 的本地化字符串。
        /// </summary>
        public static string MyCenter {
            get {
                return ResourceManager.GetString("MyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的下载 的本地化字符串。
        /// </summary>
        public static string MyDownSongs {
            get {
                return ResourceManager.GetString("MyDownSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的兆赫 的本地化字符串。
        /// </summary>
        public static string MyHz {
            get {
                return ResourceManager.GetString("MyHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的红心兆赫 的本地化字符串。
        /// </summary>
        public static string MyLoveHz {
            get {
                return ResourceManager.GetString("MyLoveHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用网络 的本地化字符串。
        /// </summary>
        public static string NoneNetwork {
            get {
                return ResourceManager.GetString("NoneNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭退出应用提醒 的本地化字符串。
        /// </summary>
        public static string OffExitTip {
            get {
                return ResourceManager.GetString("OffExitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前操作失败,请检查网络或重试 的本地化字符串。
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他设置 的本地化字符串。
        /// </summary>
        public static string OtherSetting {
            get {
                return ResourceManager.GetString("OtherSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不一致 的本地化字符串。
        /// </summary>
        public static string PasswordEqual {
            get {
                return ResourceManager.GetString("PasswordEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含英文和数字,最少8位 的本地化字符串。
        /// </summary>
        public static string PasswordTip {
            get {
                return ResourceManager.GetString("PasswordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] pivot1 {
            get {
                object obj = ResourceManager.GetObject("pivot1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 当前歌曲文件出错，请重新下载 的本地化字符串。
        /// </summary>
        public static string PlayLocalSongError {
            get {
                return ResourceManager.GetString("PlayLocalSongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册新账号 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即注册 的本地化字符串。
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由英文和数字组成 的本地化字符串。
        /// </summary>
        public static string RegisterTip {
            get {
                return ResourceManager.GetString("RegisterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复密码 的本地化字符串。
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在使用#name#网络 的本地化字符串。
        /// </summary>
        public static string ShowNetwork {
            get {
                return ResourceManager.GetString("ShowNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该歌曲已经下载 的本地化字符串。
        /// </summary>
        public static string SongIsDown {
            get {
                return ResourceManager.GetString("SongIsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string SongLoaded {
            get {
                return ResourceManager.GetString("SongLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始体验 的本地化字符串。
        /// </summary>
        public static string StartApp {
            get {
                return ResourceManager.GetString("StartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击搜索歌词 的本地化字符串。
        /// </summary>
        public static string TapLoadLyr {
            get {
                return ResourceManager.GetString("TapLoadLyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题设置 的本地化字符串。
        /// </summary>
        public static string ThemeSetting {
            get {
                return ResourceManager.GetString("ThemeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击右上角图标可从本地图库选择你喜欢的主题图片哦~~ 的本地化字符串。
        /// </summary>
        public static string ThemeSettingTip {
            get {
                return ResourceManager.GetString("ThemeSettingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 :  的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微博 的本地化字符串。
        /// </summary>
        public static string Weibo {
            get {
                return ResourceManager.GetString("Weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文简体 的本地化字符串。
        /// </summary>
        public static string ZhLang {
            get {
                return ResourceManager.GetString("ZhLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文繁体 的本地化字符串。
        /// </summary>
        public static string ZhTwLang {
            get {
                return ResourceManager.GetString("ZhTwLang", resourceCulture);
            }
        }
    }
}
