//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DouBanFMBase.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DouBanFMBase.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账号登陆 的本地化字符串。
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部赫兹 的本地化字符串。
        /// </summary>
        public static string AllHz {
            get {
                return ResourceManager.GetString("AllHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单项 的本地化字符串。
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的应用程序 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换账号 的本地化字符串。
        /// </summary>
        public static string ChangeAccount {
            get {
                return ResourceManager.GetString("ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏赫兹 的本地化字符串。
        /// </summary>
        public static string CollectHz {
            get {
                return ResourceManager.GetString("CollectHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义主题 的本地化字符串。
        /// </summary>
        public static string CustomTheme {
            get {
                return ResourceManager.GetString("CustomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 猜你喜欢 的本地化字符串。
        /// </summary>
        public static string DoyouLike {
            get {
                return ResourceManager.GetString("DoyouLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击加载频道列表 的本地化字符串。
        /// </summary>
        public static string LoadChannelTip {
            get {
                return ResourceManager.GetString("LoadChannelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先登录 的本地化字符串。
        /// </summary>
        public static string LoginFirst {
            get {
                return ResourceManager.GetString("LoginFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人中心 的本地化字符串。
        /// </summary>
        public static string MyCenter {
            get {
                return ResourceManager.GetString("MyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的下载 的本地化字符串。
        /// </summary>
        public static string MyDownSongs {
            get {
                return ResourceManager.GetString("MyDownSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的赫兹 的本地化字符串。
        /// </summary>
        public static string MyHz {
            get {
                return ResourceManager.GetString("MyHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击搜索歌词 的本地化字符串。
        /// </summary>
        public static string TapLoadLyr {
            get {
                return ResourceManager.GetString("TapLoadLyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题设置 的本地化字符串。
        /// </summary>
        public static string ThemeSetting {
            get {
                return ResourceManager.GetString("ThemeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击右上角图标可从本地图库选择你喜欢的主题图片哦~~ 的本地化字符串。
        /// </summary>
        public static string ThemeSettingTip {
            get {
                return ResourceManager.GetString("ThemeSettingTip", resourceCulture);
            }
        }
    }
}
